environment:
  QTDIR: C:/Qt/5.15/msvc2017_64
  BOOST_ROOT: C:/Libraries/boost_1_73_0

configuration: Release

image: Visual Studio 2019
platform: x64

install:
  - appveyor DownloadFile "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/unsis/nsis-2.46.5-Unicode-setup.exe" -FileName nsis.exe
  - nsis.exe /S
  - appveyor DownloadFile "https://github.com/ossia/score-sdk/releases/download/sdk9/win-audio-sdk.zip" -FileName win-audio-sdk.zip
  - 7z x win-audio-sdk.zip
  - appveyor DownloadFile "http://download.qt.io/official_releases/jom/jom.zip" -FileName jom.zip
  - 7z x jom.zip
  - move portaudio c:\portaudio
  - move ffmpeg c:\ffmpeg

build_script:
  - git submodule update --init --recursive
  - set PATH=%CD%;%PATH%
  - mkdir build
  - cd build
  - dir C:/Qt
  - dir C:/Qt/5.15
  - dir %QTDIR%  
  - dir %QTDIR%/lib/cmake/Qt5

  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64
  - cmake -G "NMake Makefiles JOM" -DCMAKE_UNITY_BUILD=1 -DSCORE_CONFIGURATION=static-release -DBOOST_ROOT="%BOOST_ROOT%" -DCMAKE_PREFIX_PATH="%QTDIR%" ..
  - cmake --build . --config Release -- -j4
  - cmake --build . --config Release --target Package

artifacts:
  - name: Installer
    path: 'build/ossia score-*.exe'
