trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'
pr:
  - '*'

variables:
  isGitTag: $[startsWith(variables['Build.SourceBranch'], 'refs/tags/')]
  gitTag: $[replace(variables['Build.SourceBranch'], 'refs/tags/', '')]
  gitTagNoV: $[replace(replace(variables['Build.SourceBranch'], 'refs/tags/v', ''), '/', '')]

stages:
  - stage: Build
    jobs:
      - job: Win32
        displayName: Win32
        pool:
          vmImage: 'windows-2019'

        steps:
        - checkout: self
          submodules: recursive

        - script: |
            cinst -y ninja
        - bash: |
            set -x            
            mkdir /c/score-sdk
            cd /c/score-sdk            
            curl -L https://github.com/ossia/sdk/releases/download/sdk15/score-sdk-mingw.7z --output score-sdk-mingw.7z
            7z x score-sdk-mingw.7z
            rm score-sdk-mingw.7z
            ls

        - script: |
            mkdir build
            cd build
            set PATH=%PATH%;c:\score-sdk\llvm\bin
            cmake -GNinja $(Build.SourcesDirectory) ^
              -DCMAKE_C_COMPILER=clang.exe ^
              -DCMAKE_CXX_COMPILER=clang++.exe ^
              -DCMAKE_BUILD_TYPE=Release ^
              -DCMAKE_EXE_LINKER_FLAGS="-static -static-libgcc -static-libstdc++" ^
              -DOSSIA_SDK=c:\score-sdk ^
              -DCMAKE_INSTALL_PREFIX=install ^
              -DCMAKE_BUILD_TYPE=Release ^
              -DCMAKE_UNITY_BUILD=1 ^
              -DDEPLOYMENT_BUILD=1
              
            cmake --build .
            cmake --build . --target package
            dir
            move "ossia score-3.0.0-win64.exe" "ossia score-$(gitTagNoV)-win64.exe"
            dir
            
          displayName: Build

        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: "$(System.DefaultWorkingDirectory)/build/ossia score-$(gitTagNoV)-win64.exe"
            artifactName: Installer

        - task: GitHubRelease@1
          condition: and(succeeded(), eq(variables.isGitTag, true))
          inputs:
            gitHubConnection: github.com_jcelerier
            repositoryName: ossia/score
            action: 'edit'
            target: '$(Build.SourceVersion)'
            tag: '$(gitTag)'
            tagSource: manual
            title: '$(gitTag)'
            assetUploadMode: 'replace'
            assets: "$(System.DefaultWorkingDirectory)/build/ossia score-$(gitTagNoV)-win64.exe"
