trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'
pr:
  - '*'

variables:
  isGitTag: $[startsWith(variables['Build.SourceBranch'], 'refs/tags/')]
  gitTag: $[replace(variables['Build.SourceBranch'], 'refs/tags/', '')]
  gitTagNoV: $[replace(replace(variables['Build.SourceBranch'], 'refs/tags/v', ''), '/', '')]

stages:
  - stage: Build
    jobs:
      - job: Win32
        displayName: Win32
        pool:
          vmImage: 'windows-2019'

        steps:
        - checkout: self
          submodules: recursive

        - script: |
            cinst -y ninja
        - bash: |
            echo " ============ "
            echo "$BUILD_ARTIFACTSTAGINGDIRECTORY"
            echo "$BUILD_SOURCESDIRECTORY"
            set -x            
            mkdir /c/score-sdk
            cd /c/score-sdk
            curl -L https://github.com/ossia/sdk/releases/download/sdk16/score-sdk-mingw.7z --output score-sdk-mingw.7z
            7z x score-sdk-mingw.7z
            rm score-sdk-mingw.7z
            ls

        - script: |
            mkdir build
            cd build
            set PATH=%PATH%;c:\score-sdk\llvm\bin
            cmake -GNinja $(Build.SourcesDirectory) ^
              -DCMAKE_C_COMPILER=c:/score-sdk/llvm/bin/clang.exe ^
              -DCMAKE_CXX_COMPILER=c:/score-sdk/llvm/bin/clang++.exe ^
              -DCMAKE_BUILD_TYPE=Release ^
              -DOSSIA_SDK=c:\score-sdk ^
              -DCMAKE_INSTALL_PREFIX=install ^
              -DCMAKE_PREFIX_PATH="c:/score-sdk/qt5-static;c:/score-sdk/llvm-libs;c:/score-sdk/SDL2;c:/score-sdk" ^
              -DCMAKE_BUILD_TYPE=Release ^
              -DCMAKE_UNITY_BUILD=1 ^
              -DOSSIA_STATIC_EXPORT=1 ^
              -DSCORE_INSTALL_HEADERS=1 ^
              -DDEPLOYMENT_BUILD=1
              
            cmake --build .
            cmake --build . --target package
            dir
            move "ossia score-3.0.0-win64.exe" "$(Build.ArtifactStagingDirectory)\ossia score-$(gitTagNoV)-win64.exe"
            dir

        - bash: |
            export SCORE_DIR="$PWD"
            export SDK_DIR="$PWD/build/SDK"
            ls
            (
              cd build
              cmake --install . --strip --component Devel --prefix "$SDK_DIR"
            )

            ./src/plugins/score-plugin-jit/tools/create-sdk-mingw.sh

            (cd build/SDK; 7z a "$BUILD_ARTIFACTSTAGINGDIRECTORY/windows-sdk.zip" usr)
            
          displayName: Build

        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: "$(Build.ArtifactStagingDirectory)/ossia score-$(gitTagNoV)-win64.exe"
            artifactName: Installer

        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: "$(Build.ArtifactStagingDirectory)/windows-sdk.zip"
            artifactName: SDK

        - task: GitHubRelease@1
          condition: and(succeeded(), eq(variables.isGitTag, true))
          inputs:
            gitHubConnection: github.com_jcelerier
            repositoryName: ossia/score
            action: 'edit'
            target: '$(Build.SourceVersion)'
            tag: '$(gitTag)'
            tagSource: manual
            title: '$(gitTag)'
            assetUploadMode: 'replace'
