trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'
pr:
  - '*'

variables:
  isGitTag: $[startsWith(variables['Build.SourceBranch'], 'refs/tags/')]
  gitTag: $[replace(variables['Build.SourceBranch'], 'refs/tags/', '')]

stages:
  - stage: Build
    jobs:
      - job: Win32
        displayName: Win32
        pool:
          vmImage: 'windows-2019'

        steps:
        - checkout: self
          submodules: true

        - script: |
            cinst -y ninja
        - bash: |
            set -x
            pwd
            mkdir /c/score-sdk
            cd /c/score-sdk
            pwd
            curl -L https://github.com/ossia/sdk/releases/download/sdk15/score-sdk-mingw.7z --output score-sdk-mingw.7z
            7z x score-sdk-mingw.7z
            rm score-sdk-mingw.7z
            ls

        - script: |
            mkdir build
            cd build
            set PATH=%PATH%;c:\score-sdk\llvm\bin
            cmake -GNinja $(Build.SourcesDirectory) -DCMAKE_C_COMPILER=clang.exe -DCMAKE_CXX_COMPILER=clang++.exe -DOSSIA_SDK=c:\score-sdk -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=Release -DSCORE_CONFIGURATION=static-release
            cmake --build .
            cmake --build . --target package
            dir
            
          displayName: Build
